stages:
 - build
 - test
build_deb_packet:
  stage: build
  image: ubuntu:latest
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt install gcc build-essential -y
  script:
    - ls
    - cd epm
    - ./configure
    - make
    - make install
    - epm epm --output-dir deb-distr
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - epm/deb-distr/
# Получить переменную и передать её в другой этап (test)
# epm --version |head -n1 |tail -c 6 > это версия epm. Нужно еще удалить пробел в конце.

#build_rpm_packet:
#  stage: build

test_deb_packet:
  stage: test
  image: ubuntu:latest
#  before_script:
#    echo test
  script:
    - ls
    - ls epm
    - ls epm/deb-distr
    - cd epm/deb-distr
    - tar -zxf epm-4.4.1-linux-4.15-x86_64.tar.gz
    - ls
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - epm/deb-distr
