stages:
 - build
 - test
build_deb_packet:
  stage: build
  image: ubuntu:latest
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt install gcc build-essential -y
  script:
    - ls
    - cd epm
    - ./configure
    - make
    - make install
    - epm epm --output-dir deb-distr
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
#      - deb-distr/
      - epm/deb-distr/
#    - cd os-major.minor-architecture
#    - docker-compose ps 
#    - docker exec crawler_crawler_1 /bin/bash -c "python3 -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include crawler/crawler.py"

#build_rpm_packet:
#  stage: build

test_deb_packet:
  stage: test
  image: ubuntu:latest
#  before_script:
#    echo test
  script:
    - ls
    - ls epm
    - ls epm/deb-distr
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - epm/deb-distr
