stages:
 - build
 - test
build_deb_packet:
  stage: build
  image: ubuntu:latest
  services:
    - docker:dind
  before_script:
    sudo apt-get update
    sudo apt install gcc build-essential    
  script:
    ls
    cd epm
    ./configure
    make
    sudo make install
    epm epm
    cd os-major.minor-architecture
#    - docker-compose ps 
#    - docker exec crawler_crawler_1 /bin/bash -c "python3 -m unittest discover -s tests/ && coverage run -m unittest discover -s tests/ && coverage report --include crawler/crawler.py"

#build_rpm_packet:
#  stage: build

test_deb_packet:
  stage: deploy
  image: alpine:latest
#  before_script:
#    echo test
  script:
    echo test
#  environment:
#    name: production
#  when: manual
