stages:
 - build
 - test
build_deb_packet:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt install gcc build-essential -y
  script:
    - cd epm
    - ./configure
    - make
    - make install
    - epm -f deb epm --output-dir deb-distr
  artifacts:
    name: "$CI_COMMIT_SHA"
    paths:
      - epm/deb-distr/

build_rpm_packet:
  stage: build
  image: centos:latest
  before_script:
    - yum update -y
    - yum groupinstall "Development Tools" -y
  script:
    - cd epm
    - ./configure
    - make
    - make install
    - epm -vvv -a noarch -f rpm epm --output-dir rpm-test1
  artifacts:
    name: "$CI_COMMIT_SHA"     
    paths:
      - epm/rpm-distr/
  when: manual

test_deb_packet:
  stage: test
  image: ubuntu:latest
  script:
    - cd epm/deb-distr
    - tar -zxf epm-4.4.1-linux-4.15-x86_64.deb.tgz
    - dpkg -i epm-4.4.1-linux-4.15-x86_64.deb
    - dpkg -l epm
  artifacts:
    name: "$CI_COMMIT_SHA"
    paths:
      - epm/deb-distr
